### PR TITLE
Add CI/CD documentation

### PR DESCRIPTION
**Pull request by kiry5273**
Issue #1 #4

### CODE REVIEW

**Comment by kiry5273** [comment]
@hero1601 @hanzhe-liu I created the documentation for cicd pipeline. Please help fill in the part you did. Thanks.

**Comment by hero1601** [comment]
ok I will add my part in the documentation

**Comment by hero1601** [comment]
added linting functionality

**Comment by hero1601** [comment]
@Sudhansh6 @jialinh4 @code123jsr @BZhang-ucsd @hanzhe-liu @matchtea Can anyone of you review the PR

**Review by akash-saranathan — APPROVED** [review]
The CI/CD pipeline includes essential components such as linting checks, unit testing, and human reviews. Future implementations can also include some more features like performance monitoring and code coverage validation to enhance the pipeline.

**Comment by BZhang-ucsd** [comment]
Is there any other function that's still in progress? The plan for future only has like few words, I don't know if its enough.

**Comment by hero1601** [comment]
No, there is no GitHub action that is in progress. Should we describe what we plan to do in documentation generation?

**Comment by kiry5273** [comment]
@hanzhe-liu Can you add on the rest of the content of the document? Or any part you have done. Thanks.

**Comment by jialinh4** [comment]
i think it looks good, i will review it later after we have finished the rest of the content of the document

**Comment by BZhang-ucsd** [comment]
> No, there is no GitHub action that is in progress. Should we describe what we plan to do in documentation generation?

Yeah I think adding a little description would be better

**Comment by hero1601** [comment]
done added description for future github actions

**Comment by kiry5273** [comment]
> done added description for future github actions

Looks good. I was thinking @hanzhe-liu can do this but thanks a lot!
I will merge the documentation into the main branch then.

**Review by matchtea — APPROVED** [review]

**Pull request merged**
