### PR TITLE
fixed eslint workflow

### PR DESCRIPTION
**Pull request by hero1601**

### CODE REVIEW

**Comment by Sudhansh6** [comment]
how do we test your changes?

**Comment by hero1601** [comment]
You can run eslint worklow in local env and see that(for now I have made all errors check to warnings so there would be a list of warnings present , we can later remove them) or you can see that in run eslint job in github worflow.
image

If you want to test my changes in your code then we need to push my changes to main.

**Review by Sudhansh6 — APPROVED** [review]
I checked the workflow demo locally, and it works. It's good to add to the main branch.

**Review by kiry5273 — APPROVED** [review]
Have tested locally it works. Can try to merge into main branch and test it out.

**Pull request merged**
