### PR TITLE
Create super-linter.yml

### PR DESCRIPTION
**Pull request by hero1601**
Added github action for code linting so that it can validate the code style

### CODE REVIEW

**Review by kiry5273 — COMMENTED** [review]
Looks good! I think we can approve this first and wait til the main code added in the repo to test out whether it is working?

**Comment by hero1601** [comment]
I tested it by adding a test.js file. So I believe it is working fine, but we might need to change the whole vs. journal code if it didn't follow a single indentation practice

**Review by kiry5273 — APPROVED** [review]
Looks good! Approved.
In the future maybe we can attach screenshot of our test result in the comment.

**Review by akash-saranathan — APPROVED** [review]
The linting process runs when code is pushed to the main branch or a pull request is created. It only lints the modified files to avoid unnecessary checks on unchanged files.  Looks good, as the checks have passed and we can make modifications in the future as required.

**Review by jialinh4 — APPROVED** [review]
i think it looks good

**Comment by hanzhe-liu** [comment]
Super Linter is used as the linting tool, which is concise and efficient. I think this works good.

**Pull request merged**
