### PR TITLE
Source code

### LINKED ISSUE #3: Setup vscode-journal code into our repo

### PR DESCRIPTION
**Pull request by Sudhansh6**
Issue #3

### CODE REVIEW

**Comment by hero1601** [comment]
You should add .node-modules in the .gitignore file because they are generated when we run npm.

**Comment by jialinh4** [comment]
since we are actually forking this from the original repo, do we need to write a documentation to give some citations or credits to the original one?

**Comment by BZhang-ucsd** [comment]
I actually merged the source code of two extensions, if that one works, do we still need this source code?

**Comment by Sudhansh6** [comment]
Can we merge this pull request if everything is working here in terms of GitHub workflows?

**Pull request closed without merging**
