### PR TITLE
Merged source code of two extension

### PR DESCRIPTION
**Pull request by BZhang-ucsd**
I have merged the vscode-journal extension and tagged extension by adapting the functionality of file tagging into the journal extension. Seems to be working fine locally.

### CODE REVIEW

**Comment by BZhang-ucsd** [comment]
There are some differences in dependencies and scripts, not sure if we should stick with the one from the source code or use the one set up in main repo.

**Review by Sudhansh6 — COMMENTED** [review]
It is not working on my end. Are there any dependencies that we have to install?

**Comment by Sudhansh6** [comment]
Installed the dependencies and tested the extensions.
- I am able to create the notes
- Able to tag files through the extension
Need to create tests for checks, otherwise looks good to me.

**Comment by hero1601** [comment]
There are some merge conflict. Can you resolve that

**Comment by jialinh4** [comment]
actually can i create another branch with this merged copy to work on the test failing problem? since it will be better for me to test the cases without any collisions on this branch with Botao

**Review by jialinh4 — APPROVED** [review]

**Comment by hero1601** [comment]
Why are we removing super-lint?

**Review by kiry5273 — APPROVED** [review]

**Comment by Sudhansh6** [comment]
> Why are we removing super-lint?
Because super lint is painful and the previous code uses ESLint

**Review by akash-saranathan — APPROVED** [review]
It looks good.

**Review by hero1601 — APPROVED** [review]

**Comment by Sudhansh6** [comment]
Tested the code, it works.

**Pull request merged**
