### PR TITLE
Tests for tagging

### PR DESCRIPTION
**Pull request by kiry5273**
Added test files for TagFile features.
All test passed on my local and the github action.
Screenshot 2024-12-08 at 9 09 21 PM

### CODE REVIEW

**Comment by jialinh4** [comment]
image
it seems like i have 1 failure running the test files and is this the issue you were talking about earlier for Syncing the notes?

**Comment by kiry5273** [comment]
> image it seems like i have 1 failure running the test files and is this the issue you were talking about earlier for Syncing the notes?

No I only fail on the sync_note test. I eventually solved this issue by deleting all the existing test file in the journal.

**Review by akash-saranathan — APPROVED** [review]
Reviewed the changes. All the checks are passed.

**Comment by Sudhansh6** [comment]
Is there a way we can fix the sync_notes test? By deleting the .journal folder before the tests start running. This way the test wouldn't fail

**Review by jialinh4 — APPROVED** [review]

**Pull request merged**
