### PR TITLE
Modified Vscode Test

### PR DESCRIPTION
**Pull request by BZhang-ucsd**
Modify all direct and suite test accoding to our code. It is all passing right now. I also modify launch.json configuration for one of the direct test that needs vscode environment.

### CODE REVIEW

**Comment by BZhang-ucsd** [comment]
testsuite_result

All 14 test in test suit are passing

**Comment by BZhang-ucsd** [comment]
All direct test can be test by running "node ./out/test/direct/＜test file name＞.js" excepts "input_parser.js". 

To test "input_parser.js" you need to launch extention development host enviornment. I have added "Run Direct Test" as a launch option in launch.json for this specific test.
Screenshot_20241124044422
It just simply prints the parsed flag in Debug Console

**Comment by hero1601** [comment]
How did you run the test script as I tried "node ./out/test/direct/.js" and it was giving error.
I also tried the "npm test", and it was giving some error.

**Comment by BZhang-ucsd** [comment]
> How did you run the test script as I tried "node ./out/test/direct/.js" and it was giving error.
> I also tried the "npm test", and it was giving some error.

For direct test first you have to compile the test file from typescript to javascript first. Then run “*node ./out/test/direct/＜test file name＞.js*“ with the direct test file name. Sorry for the confusion 

There shouldn’t be errors for “npm test” since it pass the vscode test on GitHub. One possible error is for test suit sync notes, you have to delete the file and notes generate by the test to run the test again.

**Comment by hero1601** [comment]
I got the issue of why the npm test was failing for me. I had the node 22 version, whereas we used node 16 in the project.

**Review by hero1601 — APPROVED** [review]
tested and it was working. As i was using node 22 so it was giving some errors but after changing to node 16 all the test case passed.

**Comment by kiry5273** [comment]
The node version in Github workflow now is 16. 
But if in the future, our other package need a newer node version (18+), we have to change test script in package.json to `vscode-test` instead of `node ./out/test/direct/.js`. 
In my branch #27, I tried to use node 20 for testing so it needs some other files for vscode-test. I think we can discuss which node version we want to use and decide which branch to keep.
The rest looks good. I also test it and it works.

**Review by kiry5273 — APPROVED** [review]

**Pull request merged**
