### PR TITLE
added direction for use documentation 

### PR DESCRIPTION
**Pull request by jialinh4**

### CODE REVIEW

**Comment by hero1601** [comment]
For how to use documentation, we need to provide information on how we can use 8x journals directly in our code base and what functionalities are present in them.

**Comment by jialinh4** [comment]
i think for now it looks fine for the document about the main features and usages

**Review by Sudhansh6 — COMMENTED** [review]
The installation instructions seem incomplete, need to fix them

**Comment by jialinh4** [comment]
fixed the content and formatting

**Review by Sudhansh6 — APPROVED** [review]
Approving...

**Review by akash-saranathan — APPROVED** [review]
Reviewed the notes.

**Pull request merged**
