### PR TITLE
Fix vscode-test

### PR DESCRIPTION
**Pull request by kiry5273**
Integrate with the change in #28. Successfully doing test using script `vscode-test` and node version 20.
Screenshot 2024-11-25 at 3 03 48 PM

### CODE REVIEW

**Comment by BZhang-ucsd** [comment]
theres 11 test being skipped, did you test them?

**Comment by kiry5273** [comment]
> theres 11 test being skipped, did you test them?

Yeah I'm still trying to make the rest of the tests work.

**Comment by BZhang-ucsd** [comment]
Can you check Pull Request #28, I have modified all test suite and direct tests to pass.

**Comment by kiry5273** [comment]
> Can you check Pull Request #28, I have modified all test suite and direct tests to pass.

Yeah that PR looks good! I integrated some of your change in this PR. If we don't need a higher version of node, we can go with your branch.

**Comment by Sudhansh6** [comment]
Do we still need this branch then?

**Comment by kiry5273** [comment]
> Do we still need this branch then?

No we chose to use Botao's branch #28 eventually

**Pull request closed without merging**
