### PR TITLE
add some test for journal view

### PR DESCRIPTION
**Pull request by hanzhe-liu**
add some test for journal view.

### CODE REVIEW

**Comment by hero1601** [comment]
We should add this test script to the documentation after we merge the documentation branch.

**Comment by kiry5273** [comment]
I see you are doing tests specifically on edge cases. Can you maybe change the file name to something similar to journa_view_edge_cases?

**Review by Sudhansh6 — COMMENTED** [review]
image

The tests work, but there are unnecessary prints

**Review by Sudhansh6 — APPROVED** [review]
Fixed it through another branch

**Review by BZhang-ucsd — APPROVED** [review]
I have fixed the prints in data provider

**Pull request merged**
